In [497]:
import pandas as pd
import numpy as np

In [498]:
df=pd.read_csv("house.csv")

In [499]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [500]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [501]:
df.shape

(13320, 9)

In [502]:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
5540,Super built-up Area,Ready To Move,Pattandur Agrahara,2 BHK,Shvarji,797,2.0,1.0,32.0
4954,Super built-up Area,22-Jun,Hoodi,2 BHK,GoAirej,1430,2.0,2.0,110.0
3519,Built-up Area,Ready To Move,Kudlu Gate,3 BHK,Brlms P,1335,3.0,2.0,89.0
1357,Super built-up Area,Ready To Move,Benson Town,3 BHK,NaN,3200,4.0,NaN,350.0
7161,Plot Area,17-Aug,Hennur,3 Bedroom,NaN,1000,3.0,1.0,130.0

In [503]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [504]:
df1=df.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [505]:
df

                       location       size total_sqft  bath   price
0      Electronic City Phase II      2 BHK       1056   2.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      Kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00
13316             Richards Town      4 BHK       3600   5.0  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00
13319              Doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [506]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [507]:
df['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [508]:
df['location']=df['location'].fillna('Sarjapur  Road')

In [509]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

size ko fill karna ha

In [510]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [511]:
df['size']=df['size'].fillna('3 BHK')

In [512]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [513]:
df['bath']=df['bath'].fillna(df['bath'].median()) # numerical value median sa fill karta ha

In [514]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

# ab hum chahey to data ko trining ka liya bhej skteey hai lekin usse phle data ki quality shi  krni hogi

In [515]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4326
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [516]:
df['size'].str.split().str.get(0)

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: object

In [517]:
df['bhk']=df['size'].str.split().str.get(0).astype(int)

In [518]:
df.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [519]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [520]:
def converRange(sqft):
    new_sqft=sqft.split("-")
    len_sqft=len(new_sqft)
    if(len_sqft==2):
        
        avg=(float(new_sqft[0])+ float(new_sqft[1]))/2
        
        return avg
    else:
        try:
            return float(new_sqft[0])
        except:
            None

In [521]:
df['total_sqft']=df['total_sqft'].apply(converRange)

In [522]:
df['total_sqft']

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: total_sqft, Length: 13320, dtype: float64

In [523]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13274 non-null  float64
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
 5   bhk         13320 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 624.5+ KB

In [524]:
df['total_sqft'].isnull().sum()

np.int64(46)

In [525]:
df=df.dropna(subset=['total_sqft'])

In [526]:
df['total_sqft'].isnull().sum()

np.int64(0)

In [527]:
df.shape

(13274, 6)

In [528]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [529]:
df['price_per_sqft']=df['price']*100000/df['total_sqft']

C:\Users\singh\AppData\Local\Temp\ipykernel_10148\1969806812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft']=df['price']*100000/df['total_sqft']

In [530]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [531]:
df['location'].value_counts()

location
Whitefield           538
Sarjapur  Road       400
Electronic City      302
Kanakpura Road       271
Thanisandra          233
                    ...
Chikkabidarakallu      1
manyata                1
LIC Colony             1
Mallappa Layout        1
Rahmath Nagar          1
Name: count, Length: 1299, dtype: int64

## yadi hum location ko as it is bhejitey hai to onehot encoder 1299 column bnayaga,isko reduce kane ke liye hum un sari location jinki value 10 se kh hai unko 'other' se replace ke denge

In [532]:
locations=df['location'].value_counts()

In [533]:
locations

location
Whitefield           538
Sarjapur  Road       400
Electronic City      302
Kanakpura Road       271
Thanisandra          233
                    ...
Chikkabidarakallu      1
manyata                1
LIC Colony             1
Mallappa Layout        1
Rahmath Nagar          1
Name: count, Length: 1299, dtype: int64

In [534]:
df['location']=df['location'].apply(lambda x:x.strip())

C:\Users\singh\AppData\Local\Temp\ipykernel_10148\3714613365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['location']=df['location'].apply(lambda x:x.strip())

In [535]:
locations=df['location'].value_counts()

In [536]:
locations_count_less_than_10=locations[locations <=10]

In [537]:
locations_count_less_than_10

location
Dodsworth Layout         10
Sector 1 HSR Layout      10
Naganathapura            10
Kalkere                  10
1st Block Koramangala    10
                         ..
pavitra paradise          1
Udayagiri                 1
Chikkajala                1
Medaralli                 1
Banagirinagar             1
Name: count, Length: 1048, dtype: int64

In [538]:
df['location']=df['location'].apply(lambda x: 'other' if x in locations_count_less_than_10 else x)

C:\Users\singh\AppData\Local\Temp\ipykernel_10148\2400860333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['location']=df['location'].apply(lambda x: 'other' if x in locations_count_less_than_10 else x)

In [539]:
locations=df['location'].value_counts()

In [540]:
df['location'].value_counts()

location
other                        2876
Whitefield                    539
Sarjapur  Road                400
Electronic City               304
Kanakpura Road                271
                             ...
2nd Phase Judicial Layout      11
Marsur                         11
Bommenahalli                   11
Doddaballapur                  11
HAL 2nd Stage                  11
Name: count, Length: 241, dtype: int64

## now

In [541]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       574.625987
std        387.572335
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [542]:
df=df[df['total_sqft']/df['bhk']>=300]

In [543]:
(df['total_sqft']/df['bhk']).describe()

count    12530.000000
mean       597.325567
std        386.960385
min        300.000000
25%        492.000000
50%        562.500000
75%        630.000000
max      26136.000000
dtype: float64

In [544]:
def remove_outlier_price_per_sqft(df):
    df_output=pd.DataFrame()
    for key , subdf in  df.groupby('location'):
        print(key)
        m=np.mean(subdf['price_per_sqft'])
        sd=np.std(subdf['price_per_sqft'])
        gen_df=subdf[(subdf['price_per_sqft']>(m-3*sd)) & (subdf['price_per_sqft']<(m+3*sd))]
        df_output = pd.concat([df_output, gen_df], ignore_index=True)
    return df_output

In [545]:
df=remove_outlier_price_per_sqft(df)

1st Block Jayanagar
1st Phase JP Nagar
2nd Phase Judicial Layout
2nd Stage Nagarbhavi
5th Block Hbr Layout
5th Phase JP Nagar
6th Phase JP Nagar
7th Phase JP Nagar
8th Phase JP Nagar
9th Phase JP Nagar
AECS Layout
Abbigere
Akshaya Nagar
Ambalipura
Ambedkar Nagar
Amruthahalli
Anandapura
Ananth Nagar
Anekal
Anjanapura
Ardendale
Arekere
Attibele
BEML Layout
BTM 2nd Stage
BTM Layout
Babusapalaya
Badavala Nagar
Balagere
Banashankari
Banashankari Stage II
Banashankari Stage III
Banashankari Stage V
Banashankari Stage VI
Banaswadi
Banjara Layout
Bannerghatta
Bannerghatta Road
Basavangudi
Basaveshwara Nagar
Battarahalli
Begur
Begur Road
Bellandur
Benson Town
Bharathi Nagar
Bhoganhalli
Billekahalli
Binny Pete
Bisuvanahalli
Bommanahalli
Bommasandra
Bommasandra Industrial Area
Bommenahalli
Brookefield
Budigere
CV Raman Nagar
Chamrajpet
Chandapura
Channasandra
Chikka Tirupathi
Chikkabanavar
Chikkalasandra
Choodasandra
Cooke Town
Cox Town
Cunningham Road
Dasanapura
Dasarahalli
Devanahalli
Devarachikkanahalli
Dodda Nekkundi
Doddaballapur
Doddakallasandra
Doddathoguru
Domlur
Dommasandra
EPIP Zone
Electronic City
Electronic City Phase II
Electronics City Phase 1
Frazer Town
GM Palaya
Garudachar Palya
Giri Nagar
Gollarapalya Hosahalli
Gottigere
Green Glen Layout
Gubbalala
Gunjur
HAL 2nd Stage
HBR Layout
HRBR Layout
HSR Layout
Haralur Road
Harlur
Hebbal
Hebbal Kempapura
Hegde Nagar
Hennur
Hennur Road
Hoodi
Horamavu Agara
Horamavu Banaswadi
Hormavu
Hosa Road
Hosakerehalli
Hoskote
Hosur Road
Hulimavu
ISRO Layout
ITPL
Iblur Village
Indira Nagar
JP Nagar
Jakkur
Jalahalli
Jalahalli East
Jigani
Judicial Layout
KR Puram
Kadubeesanahalli
Kadugodi
Kaggadasapura
Kaggalipura
Kaikondrahalli
Kalena Agrahara
Kalyan nagar
Kambipura
Kammanahalli
Kammasandra
Kanakapura
Kanakpura Road
Kannamangala
Karuna Nagar
Kasavanhalli
Kasturi Nagar
Kathriguppe
Kaval Byrasandra
Kenchenahalli
Kengeri
Kengeri Satellite Town
Kereguddadahalli
Kodichikkanahalli
Kodigehaali
Kodigehalli
Kodihalli
Kogilu
Konanakunte
Koramangala
Kothannur
Kothanur
Kudlu
Kudlu Gate
Kumaraswami Layout
Kundalahalli
LB Shastri Nagar
Laggere
Lakshminarayana Pura
Lingadheeranahalli
Magadi Road
Mahadevpura
Mahalakshmi Layout
Mallasandra
Malleshpalya
Malleshwaram
Marathahalli
Margondanahalli
Marsur
Mico Layout
Munnekollal
Murugeshpalya
Mysore Road
NGR Layout
NRI Layout
Nagarbhavi
Nagasandra
Nagavara
Nagavarapalya
Narayanapura
Neeladri Nagar
Nehru Nagar
OMBR Layout
Old Airport Road
Old Madras Road
Padmanabhanagar
Pai Layout
Panathur
Parappana Agrahara
Pattandur Agrahara
Poorna Pragna Layout
Prithvi Layout
R.T. Nagar
Rachenahalli
Raja Rajeshwari Nagar
Rajaji Nagar
Rajiv Nagar
Ramagondanahalli
Ramamurthy Nagar
Rayasandra
Sahakara Nagar
Sanjay nagar
Sarakki Nagar
Sarjapur
Sarjapur  Road
Sarjapura - Attibele Road
Sector 2 HSR Layout
Sector 7 HSR Layout
Seegehalli
Shampura
Shivaji Nagar
Singasandra
Somasundara Palya
Sompura
Sonnenahalli
Subramanyapura
Sultan Palaya
TC Palaya
Talaghattapura
Thanisandra
Thigalarapalya
Thubarahalli
Tindlu
Tumkur Road
Ulsoor
Uttarahalli
Varthur
Varthur Road
Vasanthapura
Vidyaranyapura
Vijayanagar
Vishveshwarya Layout
Vishwapriya Layout
Vittasandra
Whitefield
Yelachenahalli
Yelahanka
Yelahanka New Town
Yelenahalli
Yeshwanthpur
other

In [546]:
df.shape

(12337, 7)

In [547]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,4 Bedroom,2400.0,4.0,450.0,4,18750.000000
4,1st Block Jayanagar,2 BHK,1000.0,3.0,60.0,2,6000.000000

In [548]:
df.drop(columns=['size','price_per_sqft'],inplace=True)

In [549]:
df

                  location  total_sqft  bath   price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.00    4
1      1st Block Jayanagar      1630.0   3.0  194.00    3
2      1st Block Jayanagar      1875.0   2.0  235.00    3
3      1st Block Jayanagar      2400.0   4.0  450.00    4
4      1st Block Jayanagar      1000.0   3.0   60.00    2
...                    ...         ...   ...     ...  ...
12332                other      1353.0   2.0  110.00    2
12333                other       812.0   1.0   26.00    1
12334                other      1440.0   2.0   63.93    3
12335                other      1075.0   2.0   48.00    2
12336                other      3600.0   5.0  400.00    4

[12337 rows x 5 columns]

In [550]:
df.to_csv("clean_data.csv")

In [551]:
from sklearn.model_selection import train_test_split

In [552]:
X=df.drop(columns=['price'])

In [553]:
X

                  location  total_sqft  bath  bhk
0      1st Block Jayanagar      2850.0   4.0    4
1      1st Block Jayanagar      1630.0   3.0    3
2      1st Block Jayanagar      1875.0   2.0    3
3      1st Block Jayanagar      2400.0   4.0    4
4      1st Block Jayanagar      1000.0   3.0    2
...                    ...         ...   ...  ...
12332                other      1353.0   2.0    2
12333                other       812.0   1.0    1
12334                other      1440.0   2.0    3
12335                other      1075.0   2.0    2
12336                other      3600.0   5.0    4

[12337 rows x 4 columns]

In [554]:
y=df['price']

In [555]:
y

0        428.00
1        194.00
2        235.00
3        450.00
4         60.00
          ...
12332    110.00
12333     26.00
12334     63.93
12335     48.00
12336    400.00
Name: price, Length: 12337, dtype: float64

In [556]:
from sklearn.model_selection import train_test_split

In [557]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [558]:
X_train

                 location  total_sqft  bath  bhk
9469       Yelachenahalli      1130.0   2.0    2
286    8th Phase JP Nagar      2600.0   4.0    4
8408       Thigalarapalya      3122.0   6.0    4
3844                Hoodi       711.0   1.0    1
1758             Budigere      1153.0   2.0    2
...                   ...         ...   ...  ...
11964               other      1449.0   3.0    3
5191       Kanakpura Road      2000.0   3.0    3
5390        Kenchenahalli      1165.0   2.0    2
860          Banashankari      1040.0   2.0    2
7270     Ramamurthy Nagar      1200.0   2.0    2

[9869 rows x 4 columns]

In [559]:
from sklearn.preprocessing import OneHotEncoder

In [560]:
ohe=OneHotEncoder()

In [561]:
ohe.fit(X[['location']])

OneHotEncoder()

In [562]:
from sklearn.linear_model import LinearRegression

In [563]:
lr=LinearRegression()

In [564]:
from sklearn.compose import make_column_transformer

In [567]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['location']),remainder='passthrough')

In [568]:
column_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['1st Block Jayanagar', '1st Phase JP Nagar',
       '2nd Phase Judicial Layout', '2nd Stage Nagarbhavi',
       '5th Block Hbr Layout', '5th Phase JP Nagar', '6th Phase JP Nagar',
       '7th Phase JP Nagar', '8th Phase JP Nagar', '9th Phase JP Nagar',
       'AECS Layout', 'Abbigere', 'Akshaya Nagar', 'Ambalipura...
       'TC Palaya', 'Talaghattapura', 'Thanisandra', 'Thigalarapalya',
       'Thubarahalli', 'Tindlu', 'Tumkur Road', 'Ulsoor', 'Uttarahalli',
       'Varthur', 'Varthur Road', 'Vasanthapura', 'Vidyaranyapura',
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur', 'other'],
      dtype=object)]),
                                 ['location'])])

In [569]:
from sklearn.pipeline import make_pipeline

In [570]:
pipe=make_pipeline(column_trans,lr)

In [571]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['1st Block Jayanagar', '1st Phase JP Nagar',
       '2nd Phase Judicial Layout', '2nd Stage Nagarbhavi',
       '5th Block Hbr Layout', '5th Phase JP Nagar', '6th Phase JP Nagar',
       '7th Phase JP Nagar', '8th Phase JP Nagar', '9th Phase JP Nagar',
       'AECS Layout',...
       'Thubarahalli', 'Tindlu', 'Tumkur Road', 'Ulsoor', 'Uttarahalli',
       'Varthur', 'Varthur Road', 'Vasanthapura', 'Vidyaranyapura',
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur', 'other'],
      dtype=object)]),
                                                  ['location'])])),
                ('linearregression', LinearRegression())])

In [572]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['1st Block Jayanagar', '1st Phase JP Nagar',
       '2nd Phase Judicial Layout', '2nd Stage Nagarbhavi',
       '5th Block Hbr Layout', '5th Phase JP Nagar', '6th Phase JP Nagar',
       '7th Phase JP Nagar', '8th Phase JP Nagar', '9th Phase JP Nagar',
       'AECS Layout',...
       'Thubarahalli', 'Tindlu', 'Tumkur Road', 'Ulsoor', 'Uttarahalli',
       'Varthur', 'Varthur Road', 'Vasanthapura', 'Vidyaranyapura',
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur', 'other'],
      dtype=object)]),
                                                  ['location'])])),
                ('linearregression', LinearRegression())])

In [574]:
from sklearn.metrics import r2_score
y_pred_lr=pipe.predict(X_test)

In [575]:
r2_score(y_test,y_pred_lr)

0.5430149713619549

In [576]:
import pickle
pickle.dump(pipe,open("hose_pred.pkl","wb"))